[build]
command = "npm run build"
publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.11.0"


[context.production.environment]
  NODE_VERSION = "14"

[context.production]
  publish = "/opt/build/repo/dist"
  command = "npm run build"